version: "3.9"

services:
  emotion_recognition:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../data:/app/data
      - ../experiments:/app/experiments
    environment:
      - PYTHONPATH=/app/src
    runtime: nvidia          # αφαιρώ άμα δεν έχω GPU
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
